require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/order_payments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OrderPayment. As you add validations to OrderPayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrderPayment.create! valid_attributes
      get order_payments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order_payment = OrderPayment.create! valid_attributes
      get order_payment_url(order_payment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_order_payment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      order_payment = OrderPayment.create! valid_attributes
      get edit_order_payment_url(order_payment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrderPayment" do
        expect {
          post order_payments_url, params: { order_payment: valid_attributes }
        }.to change(OrderPayment, :count).by(1)
      end

      it "redirects to the created order_payment" do
        post order_payments_url, params: { order_payment: valid_attributes }
        expect(response).to redirect_to(order_payment_url(OrderPayment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrderPayment" do
        expect {
          post order_payments_url, params: { order_payment: invalid_attributes }
        }.to change(OrderPayment, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post order_payments_url, params: { order_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_payment" do
        order_payment = OrderPayment.create! valid_attributes
        patch order_payment_url(order_payment), params: { order_payment: new_attributes }
        order_payment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the order_payment" do
        order_payment = OrderPayment.create! valid_attributes
        patch order_payment_url(order_payment), params: { order_payment: new_attributes }
        order_payment.reload
        expect(response).to redirect_to(order_payment_url(order_payment))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        order_payment = OrderPayment.create! valid_attributes
        patch order_payment_url(order_payment), params: { order_payment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested order_payment" do
      order_payment = OrderPayment.create! valid_attributes
      expect {
        delete order_payment_url(order_payment)
      }.to change(OrderPayment, :count).by(-1)
    end

    it "redirects to the order_payments list" do
      order_payment = OrderPayment.create! valid_attributes
      delete order_payment_url(order_payment)
      expect(response).to redirect_to(order_payments_url)
    end
  end
end
